/* 
    Adding Tab JavaScript Code 
*/

/*
    Function to set the first tab as active on page load.
    It displays the content of the first tab and adds the "active" class to its corresponding tab link.
*/

function loadTab() {
    // Get the first tab and its corresponding tab link
    const firstTab = document.getElementById("tab1");
    if (firstTab) {
        // Display the content of the first tab
        firstTab.style.display = "block";
        
        // Get the first tab link and add the "active" class to it
        const firstTabLink = document.querySelector(".tablinks");
        if (firstTabLink) {
            firstTabLink.classList.add("active");
        }
    }
}

// Call the function to set the default tab on DOM Content Loaded
window.addEventListener("DOMContentLoaded", loadTab);

/*
    Function to handle tab switching.
    It hides all tab contents, removes the "active" class from all tab links,
    displays the content of the selected tab, and adds the "active" class to its tab link.

    @param {Event} event - The event object generated by the tab click.
    @param {string} tabName - The ID of the tab to be displayed.
*/

function openTab(event, tabName) {
    // Hide all tab contents
    const tabcontent = document.getElementsByClassName("tabcontent");
    for (let i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    
    // Remove the "active" class from all tab links
    const tablinks = document.getElementsByClassName("tablinks");
    for (let i = 0; i < tablinks.length; i++) {
        tablinks[i].classList.remove("active");
    }
    
    // Display the content of the selected tab
    document.getElementById(tabName).style.display = "block";
    // Add the "active" class to the clicked tab link
    event.currentTarget.classList.add("active");
}

/* 
    Adding Tab JavaScript Code 
*/